#!/usr/bin/env python
# -*- coding:utf-8 -*-

import numpy as np 
import matplotlib.pyplot as plt
import lammps_wrapper as lmp
from pprint import pprint

print('Starting...')

# Creates a setup for Lammps, used to generate a runnable Lammps file
setup = lmp.Lammmps_setup()

# Generate the Lammps file
setup.gen_lmp_file('test.in')

# Run the Lammps file
lmp.run_lammps('test.in', actually_run=False)

# Read the log generated by Lammps
data = lmp.read_log('log.lammps')

# Example of how to access data
steps = data['step']
temps = data['temp']
press = data['press']

# Plot the data. This part shouldn't be run on Hebbe
plt.plot(steps, press)
plt.show()

print('All done!')